version: '3.7'

services:
  client-react-nginx:
    image: 339712786123.dkr.ecr.us-east-2.amazonaws.com/client-react:1.0
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped
    
  api-node:
    image: 339712786123.dkr.ecr.us-east-2.amazonaws.com/api-node:2.0
    read_only: true
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    init: true
    restart: unless-stopped
  
networks:
  frontend:
  backend:
