version: '3.7'

services:
  client-react-nginx:
    image: 339712786123.dkr.ecr.us-east-2.amazonaws.com/client-react:1.0
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  api-node:
    image: 339712786123.dkr.ecr.us-east-2.amazonaws.com/api-node:2.0
    read_only: true
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    init: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/usr/src/app/healthcheck.js"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  

networks:
  frontend:
  backend:
