version: '3'
services:
  my-app:
   image: ${docker-registry}/my-app:1.0
   ports:
      - 3000:3000
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hemovic11*
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local
